import { nodeId } from "../ids";
import {
  NHL_ID,
  SEASON_2026,
  coach,
  contract,
  draftPick,
  edge,
  game,
  injury,
  line,
  playedFor,
  player,
  prospect,
  roster,
  transaction,
} from "./builders";
import { NHL_CAP_CEILING_2026 } from "./catalog";
import type { FocusPack } from "./focus-pack";

const TEAM = nodeId("team", "new-york-islanders");
const AFFILIATE = nodeId("team", "hamilton-hammers");
const DRAFT_2025 = nodeId("draft", "nhl-2025");

const p = {
  barzal: player({ firstName: "Mathew", lastName: "Barzal", sweaterNumber: 13, position: "C", shootsCatches: "R", nationality: "CA", birthDate: "1997-05-26", captaincy: "A" }),
  horvat: player({ firstName: "Bo", lastName: "Horvat", sweaterNumber: 14, position: "C", shootsCatches: "L", nationality: "CA", birthDate: "1995-04-05", captaincy: "A" }),
  lee: player({ firstName: "Anders", lastName: "Lee", sweaterNumber: 27, position: "LW", shootsCatches: "L", nationality: "US", birthDate: "1990-07-03", captaincy: "C" }),
  holmstrom: player({ firstName: "Simon", lastName: "Holmstrom", slug: "simon-holmstrom", sweaterNumber: 10, position: "RW", shootsCatches: "L", nationality: "SE", birthDate: "2001-05-24" }),
  pageau: player({ firstName: "Jean-Gabriel", lastName: "Pageau", sweaterNumber: 44, position: "C", shootsCatches: "R", nationality: "CA", birthDate: "1992-11-11" }),
  heineman: player({ firstName: "Emil", lastName: "Heineman", sweaterNumber: 51, position: "LW", shootsCatches: "L", nationality: "SE", birthDate: "2001-11-16" }),
  duclair: player({ firstName: "Anthony", lastName: "Duclair", sweaterNumber: 11, position: "LW", shootsCatches: "L", nationality: "CA", birthDate: "1995-08-26" }),
  cizikas: player({ firstName: "Casey", lastName: "Cizikas", sweaterNumber: 53, position: "C", shootsCatches: "L", nationality: "CA", birthDate: "1991-02-27" }),
  drouin: player({ firstName: "Jonathan", lastName: "Drouin", sweaterNumber: 29, position: "LW", shootsCatches: "L", nationality: "CA", birthDate: "1995-03-28" }),
  palmieri: player({ firstName: "Kyle", lastName: "Palmieri", sweaterNumber: 21, position: "RW", shootsCatches: "R", nationality: "US", birthDate: "1991-02-01" }),
  schenn: player({ firstName: "Brayden", lastName: "Schenn", sweaterNumber: 10, position: "C", shootsCatches: "L", nationality: "CA", birthDate: "1991-08-22" }),
  schaefer: player({ firstName: "Matthew", lastName: "Schaefer", sweaterNumber: 48, position: "D", shootsCatches: "L", nationality: "CA", birthDate: "2007-09-05", summary: "2025 1st overall. Calder Trophy, 2025-26." }),
  pulock: player({ firstName: "Ryan", lastName: "Pulock", sweaterNumber: 6, position: "D", shootsCatches: "R", nationality: "CA", birthDate: "1994-10-06" }),
  pelech: player({ firstName: "Adam", lastName: "Pelech", sweaterNumber: 3, position: "D", shootsCatches: "L", nationality: "CA", birthDate: "1994-08-16" }),
  deangelo: player({ firstName: "Tony", lastName: "DeAngelo", sweaterNumber: 77, position: "D", shootsCatches: "R", nationality: "US", birthDate: "1995-10-24" }),
  romanov: player({ firstName: "Alexander", lastName: "Romanov", sweaterNumber: 28, position: "D", shootsCatches: "L", nationality: "RU", birthDate: "2000-01-06" }),
  mayfield: player({ firstName: "Scott", lastName: "Mayfield", sweaterNumber: 24, position: "D", shootsCatches: "R", nationality: "US", birthDate: "1992-10-14" }),
  sorokin: player({ firstName: "Ilya", lastName: "Sorokin", sweaterNumber: 30, position: "G", shootsCatches: "L", nationality: "RU", birthDate: "1995-08-04" }),
  rittich: player({ firstName: "David", lastName: "Rittich", sweaterNumber: 33, position: "G", shootsCatches: "L", nationality: "CZ", birthDate: "1992-08-19" }),
  engvall: player({ firstName: "Pierre", lastName: "Engvall", sweaterNumber: 18, position: "LW", shootsCatches: "L", nationality: "SE", birthDate: "1996-05-31" }),
  eklund: player({ firstName: "Victor", lastName: "Eklund", sweaterNumber: 68, position: "RW", shootsCatches: "R", nationality: "SE", birthDate: "2006-10-03" }),
};

const deboer = coach({ name: "Peter DeBoer", role: "head", teamId: TEAM, seasonId: SEASON_2026 });
const players = Object.values(p);

export const islandersPack: FocusPack = {
  teamSlug: "new-york-islanders",
  players,
  coaches: [deboer],
  roster: roster({
    slug: "nyi-2025-26",
    name: "Islanders 2025-26 roster",
    teamId: TEAM,
    seasonId: SEASON_2026,
    kind: "nhl",
  }),
  contracts: [
    contract({ slug: "nyi-sorokin", playerId: p.sorokin.id, teamId: TEAM, seasonStart: 2024, seasonEnd: 2031, aavUsd: 8_250_000, years: 8, expiry: "UFA", contractType: "standard", illustrative: true }),
    contract({ slug: "nyi-horvat", playerId: p.horvat.id, teamId: TEAM, seasonStart: 2023, seasonEnd: 2031, aavUsd: 8_500_000, years: 8, expiry: "UFA", contractType: "standard", illustrative: true }),
    contract({ slug: "nyi-barzal", playerId: p.barzal.id, teamId: TEAM, seasonStart: 2022, seasonEnd: 2031, aavUsd: 9_150_000, years: 8, expiry: "UFA", contractType: "standard", illustrative: true }),
    contract({ slug: "nyi-lee", playerId: p.lee.id, teamId: TEAM, seasonStart: 2019, seasonEnd: 2026, aavUsd: 7_000_000, years: 7, expiry: "UFA", contractType: "standard", illustrative: true }),
    contract({ slug: "nyi-schaefer", playerId: p.schaefer.id, teamId: TEAM, seasonStart: 2025, seasonEnd: 2028, aavUsd: 975_000, years: 3, expiry: "RFA", contractType: "elc", illustrative: true }),
  ],
  injuries: [
    injury({
      slug: "nyi-engvall-ankle",
      name: "Pierre Engvall — ankle",
      playerId: p.engvall.id,
      teamId: TEAM,
      status: "ltir",
      bodyPart: "Ankle",
      injuredOn: "2025-09-18",
      notes: "Missed remainder of 2025-26.",
    }),
  ],
  transactions: [
    transaction({
      slug: "nyi-deboer-hire",
      name: "Islanders hire Peter DeBoer",
      kind: "signing",
      date: "2026-04-22",
      toTeamId: TEAM,
      playerIds: [],
      notes: "Coaching change after Patrick Roy. Graph models coaches as first-class nodes.",
    }),
    transaction({
      slug: "nyi-schenn-deadline",
      name: "Islanders acquire Brayden Schenn",
      kind: "trade",
      date: "2026-03-06",
      toTeamId: TEAM,
      playerIds: [p.schenn.id],
      notes: "Deadline addition; illustrative notes pending official asset return.",
    }),
  ],
  prospects: [
    prospect({ slug: "nyi-eklund", name: "Victor Eklund", playerId: p.eklund.id, teamId: TEAM, rank: 1, eta: "2026-27", leagueHint: "SHL / NHL look" }),
  ],
  picks: [
    draftPick({
      slug: "nyi-2025-1-1",
      name: "2025 1st overall — Matthew Schaefer",
      draftId: DRAFT_2025,
      round: 1,
      overall: 1,
      originalTeamId: TEAM,
      currentTeamId: TEAM,
      year: 2025,
      playerId: p.schaefer.id,
    }),
    draftPick({
      slug: "nyi-2026-2",
      name: "2026 2nd-round pick (owned)",
      draftId: nodeId("draft", "nhl-2026"),
      round: 2,
      originalTeamId: TEAM,
      currentTeamId: TEAM,
      year: 2026,
    }),
  ],
  games: [
    game({
      slug: "2026-04-14-car-nyi",
      name: "Hurricanes 2, Islanders 1",
      seasonId: SEASON_2026,
      leagueId: NHL_ID,
      homeTeamId: TEAM,
      awayTeamId: nodeId("team", "carolina-hurricanes"),
      startsAt: "2026-04-14T23:00:00Z",
      venueId: nodeId("arena", "ubs-arena"),
      status: "final",
      homeScore: 1,
      awayScore: 2,
    }),
    game({
      slug: "2026-10-preview-nyi-nyr",
      name: "Islanders vs Rangers (2026-27 shell)",
      seasonId: nodeId("season", "nhl-2026-27"),
      leagueId: NHL_ID,
      homeTeamId: TEAM,
      awayTeamId: nodeId("team", "new-york-rangers"),
      startsAt: "2026-10-12T23:00:00Z",
      venueId: nodeId("arena", "ubs-arena"),
      status: "scheduled",
    }),
  ],
  lines: [
    line(TEAM, "f1", [p.horvat.id, p.barzal.id, p.holmstrom.id], "1F"),
    line(TEAM, "f2", [p.lee.id, p.pageau.id, p.heineman.id], "2F"),
    line(TEAM, "f3", [p.duclair.id, p.cizikas.id, p.drouin.id], "3F"),
    line(TEAM, "f4", [p.palmieri.id, p.schenn.id], "4F"),
    line(TEAM, "d1", [p.schaefer.id, p.pulock.id], "1D"),
    line(TEAM, "d2", [p.pelech.id, p.deangelo.id], "2D"),
    line(TEAM, "d3", [p.romanov.id, p.mayfield.id], "3D"),
    line(TEAM, "g", [p.sorokin.id, p.rittich.id], "G"),
    line(TEAM, "pp1", [p.horvat.id, p.barzal.id, p.lee.id, p.schaefer.id, p.pulock.id], "PP1"),
    line(TEAM, "pk1", [p.pageau.id, p.cizikas.id, p.pelech.id, p.mayfield.id], "PK1"),
  ],
  cap: {
    teamId: TEAM,
    seasonId: SEASON_2026,
    ceilingUsd: NHL_CAP_CEILING_2026,
    committedUsd: 91_200_000,
    spaceUsd: 4_300_000,
    ltirUsedUsd: 2_600_000,
    notes: "Illustrative cap rollup for Phase 1. Replace with live CapFriendly/NHL feed later.",
  },
  extraNodes: [],
  extraEdges: [
    ...players.map((pl) => playedFor(pl.id, TEAM)),
    edge("coached_by", TEAM, deboer.id, { seasonId: SEASON_2026, extraKey: SEASON_2026 }),
    edge("drafted_by", p.schaefer.id, TEAM, { extraKey: "2025" }),
    edge("drafted_by", p.barzal.id, TEAM, { extraKey: "2015" }),
    edge("drafted_by", p.sorokin.id, TEAM, { extraKey: "2014" }),
    edge("rights_owned_by", p.eklund.id, TEAM),
    edge("affiliate_of", AFFILIATE, TEAM),
    edge("member_of_line", p.horvat.id, p.barzal.id, { extraKey: "nyi-f1", properties: { unit: "f1" } }),
    edge("linemate_with", p.horvat.id, p.barzal.id, { extraKey: "nyi-f1", seasonId: SEASON_2026 }),
    edge("linemate_with", p.barzal.id, p.holmstrom.id, { extraKey: "nyi-f1", seasonId: SEASON_2026 }),
    edge("contract_with", p.sorokin.id, TEAM, { extraKey: "nyi-sorokin" }),
    edge("contract_with", p.horvat.id, TEAM, { extraKey: "nyi-horvat" }),
    edge("contract_with", p.barzal.id, TEAM, { extraKey: "nyi-barzal" }),
    edge("represented_by", p.barzal.id, nodeId("agent", "pat-brisson")),
    edge("represented_by", p.sorokin.id, nodeId("agent", "paul-theofanous")),
  ],
};
